### ISSUE TITLE
V3

### ISSUE THREAD

**Issue by gldamsteegt** [NAD-ITS/alps-wordpress-nad#4]
v3

**Describe the bug**
Secondary menu overlaps Search button.

<img width="2085" alt="Screen Shot 2023-01-10 at 2 28 51 PM" src="https://user-images.githubusercontent.com/117782251/211643809-0fad196c-66dd-4770-bde0-17634b99933d.png">

**Comment by designerbrent** [comment]
This should be corrected now with the most recent version. If not, feel free to reopen the ticket.
